FROM openhd/2020-05-27-raspios-buster-lite-armhf:v2

COPY .git /data/.git/

COPY . /data/

RUN apt update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh armhf raspbian buster docker
