FROM openhd/tegra_linux_sample-root-filesystem_r32.4.2_aarch64:v1

COPY .git /data/.git/

COPY . /data/

RUN apt update

RUN apt -y install git

RUN apt -y install ruby-dev

RUN apt -y install python-pip python-setuptools

RUN apt -y purge python-configparser

RUN gem install fpm

RUN pip install cloudsmith-cli==0.23.0

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh arm64 ubuntu bionic docker
