FROM ghcr.io/openhd/tegra_linux_32.4.2_aarch64

COPY .git /data/.git/

COPY . /data/

RUN apt update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh arm64 ubuntu bionic docker
