FROM openhd/2018-10-09-raspbian-stretch-lite:v2

COPY .git /data/.git/

COPY . /data/

RUN apt update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh armhf raspbian stretch docker
