FROM openhd/tegra_linux_sample-root-filesystem_r32.4.2_aarch64:v2

COPY .git /data/.git/

COPY . /data/

RUN apt update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh arm64 ubuntu bionic docker
