#ifndef DECODINGSTATISTCS_H
#define DECODINGSTATISTCS_H

#include <QObject>

// Really nice, this way we don't have to write all the setters / getters / signals ourselves !
#include "../../lib/lqtutils_master/lqtutils_prop.h"

/**
 * @brief Simple QT model (signals) to expose QOpenHD decoding statistics to the UI.
 * singleton, corresponding qt name is "_decodingStatistics" (see main)
 * NOTE: r.n unused, and even if we use it, only data that is created by QOpenHD shuld land here -
 * .e.g the Bitrate the HW decoder reports, or similar.
 * Data generated by OpenHD itself should (e.g. the encoder stats from the air pi) should be handled by ../openhd_systems
 */
class DecodingStatistcs : public QObject
{
    Q_OBJECT
    L_RW_PROP(QString, decode_time, set_decode_time, "?")
    L_RW_PROP(QString, decode_and_render_time, set_decode_and_render_time, "?")
    L_RW_PROP(int, n_dropped_frames, set_n_dropped_frames, -1)
    L_RW_PROP(int, n_rendered_frames, set_n_rendered_frames, -1)
    L_RW_PROP(int, udp_rx_bitrate, set_udp_rx_bitrate, -1)
    L_RW_PROP(QString, doing_wait_for_frame_decode, set_doing_wait_for_frame_decode, "?")
    L_RW_PROP(QString, primary_stream_frame_format, set_primary_stream_frame_format, "?")
public:
    explicit DecodingStatistcs(QObject *parent = nullptr);
    static DecodingStatistcs& instance();
};

#endif // DECODINGSTATISTCS_H
