name: build_package_radxa_arm64_debian

on:
  workflow_dispatch:
  push:
    branches:
      - "2.7-evo"
      - "dev-release"
      - "release"
      - "rapha-dev"
      - "openhd-3.0"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/cross_package.yml
    with:
      target: rock-bookworm-arm64
    secrets: inherit
