name: build_package_x86

on:
  push:
    branches: [ "2.4-evo" ]
  pull_request:
      branches: [ "2.4-evo" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        ls -a
        sudo apt update
        sudo apt install -y curl
        sudo rm -Rf /etc/apt/sources.list.d/openhd*
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo ./install_build_dep.sh ubuntu-x86 custom

    - name: Build with make
      run: |
        curl -1sLf \
        'https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/setup.deb.sh' \
        | sudo -E bash
        sudo ./package.sh x86_64 ubuntu focal
    
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "ubuntu"
        release: "focal"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
       

