name: build_package_x86_23.04

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    container:
      image: docker://ubuntu:lunar
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          apt update
          apt install -y git sudo

      - name: clone QOpenHD
        run: |
          git clone https://github.com/OpenHD/QOpenHD --recursive
          apt install -y ruby-dev python3-pip python3-future python3-pyqt5 python3-pyqt5.qtopengl python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-pyqtgraph
          gem install fpm

      - name: Install Dependencies
        run: |
          ls
          cd QOpenHD
          ./install_build_dep.sh ubuntu-x86

      - name: Build with make
        run: |
          cd QOpenHD
          ./package.sh x86_64 ubuntu lunar
          ls -a

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "QOpenHD"
          path: |
            QOpenHD/*.deb
            *.log
          if-no-files-found: error

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-3-evo"
          distro: "ubuntu"
          release: "lunar"
          republish: "true" # needed ONLY if version is not changing
          file: "QOpenHD/*.deb"
