name: build_package_NOBLE

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-24.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: clone QOpenHD
        run: |
          git clone -b ${{ github.ref_name }} https://github.com/OpenHD/QOpenHD --recursive

      - name: Install Dependencies
        run: |
          ls
          cd QOpenHD
          sudo apt install -y python3-pip
          pip install cloudsmith-api --break-system-packages
          pip install cloudsmith-cli --break-system-packages
          sudo -H ./install_build_dep.sh ubuntu-x86

      - name: Build with make
        run: |
          cd QOpenHD
          ./package.sh regular x86_64 ubuntu noble
          ls -a

      - name: Upload to Github
        uses: 'actions/upload-artifact@v4'
        with:
          name: "QOpenHD"
          path: |
            QOpenHD/*.deb
            *.log
          if-no-files-found: error

      # - name: Push
      #   id: push
      #   uses: cloudsmith-io/action@master
      #   with:
      #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      #     command: "push"
      #     format: "deb"
      #     owner: "openhd"
      #     repo: ${{ github.ref_name }}
      #     distro: "ubuntu"
      #     release: "noble"
      #     republish: "true" # needed ONLY if version is not changing
      #     file: "QOpenHD/*.deb"
      #   if: ${{ github.ref != 'refs/heads/2.5-evo' }}

      - name: Push
        if: github.ref_name == 'release' || github.ref_name == 'dev-release'
        run: |
          ls -a
          cloudsmith push deb  -k ${{ secrets.CLOUDSMITH_API_KEY }} openhd/${{ github.ref_name }}/ubuntu/noble QOpenHD/*.deb
