name: build_package_x86_22

on:
  push:
    branches: [ "2.3-evo" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        ls -a
        sudo apt update
        sudo apt upgrade -y
        sudo apt remove libunwind-13-dev 
        sudo apt install -y libunwind-dev libgstreamer-plugins-base1.0-dev
        sudo apt install -y curl
        sudo rm -Rf /etc/apt/sources.list.d/openhd*
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt upgrade -y
        sudo add-apt-repository universe
        curl -1sLf \
        'https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/setup.deb.sh' \
        | sudo -E bash
        sudo bash install_dep_ubuntu22_release.sh
        
        

    - name: Build with make
      run: |
        sudo rm -f /etc/ld.so.conf.d/qt.conf
        sudo touch /etc/ld.so.conf.d/qt.conf
        sudo sh -c 'echo "/opt/Qt5.15.7/lib/" >/etc/ld.so.conf.d/qt.conf'
        sudo ldconfig
        export PATH="$PATH:/opt/Qt5.15.7/bin/"
        sudo rm -f /usr/bin/qmake
        sudo ln -s /opt/Qt5.15.7/bin/qmake /usr/bin/qmake
        echo "QT successfully linked"   
        sudo ./package.sh x86_64 ubuntu jammy
    
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "ubuntu"
        release: "jammy"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
       

