name: build_package_rpi5_bookworm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/cross_package.yml
    with:
      target: pi-bookworm-arm64
    secrets: inherit
