name: build_package_NOBLE

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "24.04"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    container:
      image: docker://ubuntu:noble
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          apt update
          apt install -y git sudo

      - name: clone QOpenHD
        run: |
          git clone -b ${{ github.ref_name }} https://github.com/OpenHD/QOpenHD --recursive

      - name: Install Dependencies
        run: |
          ls
          cd QOpenHD
          sudo -H ./install_build_dep.sh ubuntu-x86

      - name: Build with make
        run: |
          cd QOpenHD
          ./package.sh x86_64 ubuntu noble
          ls -a

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "QOpenHD"
          path: |
            QOpenHD/*.deb
            *.log
          if-no-files-found: error

      # - name: Push
      #   id: push
      #   uses: cloudsmith-io/action@master
      #   with:
      #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      #     command: "push"
      #     format: "deb"
      #     owner: "openhd"
      #     repo: ${{ github.ref_name }}
      #     distro: "ubuntu"
      #     release: "noble"
      #     republish: "true" # needed ONLY if version is not changing
      #     file: "QOpenHD/*.deb"
      #  if: ${{ github.ref != 'refs/heads/2.5-evo' }}